### ISSUE TITLE
Functional programming link broken

### ISSUE THREAD

**Issue by smangham** [softwaresaved/az-intermediate-software-skills-course#20]
The functional programming link here: https://softwaresaved.github.io/az-intermediate-software-skills-course/31-software-paradigms/index.html#procedural-programming
Is broken.

**Comment by jag1g13** [comment]
Thanks Sam, will remove link now - we dropped that content from this version of the course

**Comment by anenadic** [comment]
This is fixed on the branch for "post pilot1 course updates".
